server:
  port: 9505

spring:
  application:
    # 应用名称
    name: share-stastics
  profiles:
    # 环境配置
    active: dev
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 192.168.200.130:8848
        namespace: d707b2cd-8895-445d-acc6-d229b4ccb096
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: deepseek-r1:1.5b
#          temperature: 0.7
